### ISSUE TITLE
GPS Longitude and Latitude Units

### ISSUE THREAD

**Issue by brucecui97** [UBCSailbot/sailbot-msg#9]
I know we discussed this in this PR https://github.com/UBCSailbot/sailbot-msg/pull/5#issuecomment-840975268, but I was wondering if we can revisit this and update the convention to just degrees?  

Just realized as I'm creating the integration test setup with the path planning team that using just degrees makes calculations easier and requires the least parsing on the software that consumes this data. (Since we're only working with "1 unit.") Open to other suggestions too thanks

**Comment by briellelaw** [comment]
I think this makes sense. 
Just want to clarify, at which point the conversion going to be made
Would it be NAV side performing conversion right after receiving from canbus?

**Comment by brucecui97** [comment]
Ya I think " NAV side performing conversion right after receiving from canbus" is most ideal (unless there is a setting on the GPS sensor itself but I highly doubt that haha)

**Comment by briellelaw** [comment]
Ok haha, sounds good to me. I'll get onto that if everyone's in agreement

**Comment by tylerlum** [comment]
Pretty easy conversion on our end, so if works better for Bruce let's do that!

**Comment by derain12** [comment]
A bit confused to what is being changed. The current output of the GPS is degrees, minutes, and decimal minutes. Are we truncating to only use degrees (ie. Given 44.58390, use only 44)?

**Comment by briellelaw** [comment]
@derain12 based on the CAN inputs+outputs, I thought the current output was DDMM.MMMMMMM
(DegreeMinutes.DecimalMinutes)
So to get decimal degrees, we gotta do something along these lines: https://www.directionsmag.com/site/latlong-converter/

Please correct me if I'm wrong. i don't know much about this degree-minutes and decimal minutes format

**Comment by derain12** [comment]
So there's multiple conventions for indicating geographic coordinates (because people want to feel unique...). The one we are getting is considered "degrees decimal minutes (DDM)". This means that DD is in degrees (0 to 359), MM. is minutes (0 to 59), and . MMMMMMM is decimal minutes (0.0000000 to 0.9999999). 

Example: 4915.7792357 is what we receive from the GPS, which translates to 49° 15.7792357' in DDM latitude. This combines with the direction (North for this example) to get the full picture. This is the same for longitude, ie. 12315.0063247 and W = 123° 15.0063247' W.

Continued, both of these can translate to Decimal Degrees (DD), which is simply 49.263333 and -123.251 (no direction required, that's indicated by the signed value for both latitude and longitude). You'll notice the degrees for DD and DDM are the same but now signed (-180 to 180 vs 0 to 180 but with direction). Much simpler to handle compared to the DDM system, which is what I assume @brucecui97 was suggesting the whole time?

This is the solution if you're wondering, which is anti-climatic lol (https://stackoverflow.com/questions/28909499/ddm-to-dd-geographic-coordinate-conversion-algorithm)

**Comment by brucecui97** [comment]
Thanks for the explanation Simon. There’s just one part I don’t quite understand “ Example: 4915.7792357 is what we receive from the GPS, which translates to 49°'15.7792357” - does this mean we have to parse a type double somehow to split the “49” from the rest “15.7792357”?  I might be wrong but I couldn’t find an elegant way to parse a type double like that, which is why originally suggested to do the conversion once and have everyone work in decimal degrees only (I.e no minutes, no seconds). Please let me know what you think thanks

**Comment by tylerlum** [comment]
I think the best way to do it is.

lat_str = str(lat)
lat_double = double(lat_str[:2]) + double(lat_str[2:])/60

**Comment by tylerlum** [comment]
Would that work for you @brucecui97?

**Comment by tylerlum** [comment]
If for some reason you can't work with str, you can divide by 100 and then turn to int. 
lat_degrees = int(lat/100)
lat_minutes = lat - lat_degrees*100
lat_double = lat_degrees + lat_minutes/60

**Comment by briellelaw** [comment]
Sorry, where do we stand on this now? 
a. Doing the single conversion to degrees upon retrieval from CAN or 
b. SOFT/CTRL doing the needed conversions?

Tyler, your code uses the data in degree-minutes? and Bruce, your code uses degrees?

**Comment by tylerlum** [comment]
We had it in degrees, but changed it to degrees-minutes when you made the change. Happy to do either. Sounds like Bruce prefers degrees alone, so how about we just use that? (option a)

**Comment by derain12** [comment]
@brucecui97 The GPS outputs the latitude/longitude (in DDM) as a string. This is then sent through the CAN Bus as two separate integer numbers where the value after the decimal is integerized. Brielle's code at the moment takes those two values and stores it as a double/float in the same format presented by the GPS (DDMM.MMMMMMM).

If desired, we can get Brielle's code to store the two raw integer values from the CAN Bus for path planning + controller to process. OR we can do the conversion to the final DD form stored as a double/float

**Comment by tylerlum** [comment]
Let's go for that. Have Brielle's code output DD as float. We don't need super high precision, and it makes things easier for us.

**Comment by brucecui97** [comment]
Thanks for the great points. Ya personally Id vote for “Have Brielle's code output DD as float” so we only do the parsing (that’s relatively complicated) once

**Comment by briellelaw** [comment]
Ok sounds good. I’ll get on it. I’ll update the msg field first so y’all aren’t blocked and can start making your changes. And then get on to actually doing the conversion
